services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smarty
      POSTGRES_PASSWORD: smarty123
      POSTGRES_DB: research_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
